networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_ENABLE_KRAFT=yes
      - BITNAMI_DEBUG=yes
  webhook:
    build:
      context: docker/webhook
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - app-tier
    environment:
      - ENVIRONMENT=docker
      - CONFIG_ROOT=/usr/src/config
      - CONFIG_PATH=infra/kafka
      - LOGURU_LEVEL=INFO
    depends_on:
      - kafka